const BUY_TOKEN_LOADING = 'BUY_TOKEN_LOADING';
const BUY_TOKEN_SUCCESS = 'BUY_TOKEN_SUCCESS';
const BUY_TOKEN_FAILURE = 'BUY_TOKEN_FAILURE';

export const buyTokenActions = {
  BUY_TOKEN_LOADING,
  BUY_TOKEN_SUCCESS,
  BUY_TOKEN_FAILURE,
};
